name: ğŸš€ Deploy Vedeshra  to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸ” Set up SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ğŸš€ Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no vedeshra.in@ssh.gb.stackcp.com << 'EOF'
            cd public_html/vedeshraindia/vedeshra
            git pull origin main --force
            php84 /usr/bin/composer install  --ignore-platform-req=ext-mongodb
            php84 artisan migrate --force
            php84 artisan config:cache
            # php artisan route:cache
            php84 artisan view:cache
            php84 artisan storage:link
            # chmod -R 775 storage bootstrap/cache
            # chown -R www-data:www-data .
          EOF
